### ISSUE TITLE
Modularise fetching

### ISSUE THREAD

**Issue by Glombort** [sonianb/github-profile-analyser#15]
https://github.com/sonianb/github-profile-analyser/blob/2bcc90743bd6079fc063d4520285719f5c2ad249/script.js#L22-L26

I think oli mentioned this a while ago but for each fetch there's a lot of repetition, so maybe consider creating a function to do this for you for tidyness

**Comment by sonianb** [comment]
I created a `callGithubAPI(apiUrl)` function to fix that and avoid repetition.
Let me know what you think :)

**Comment by Glombort** [comment]
Yee looks a crackin' good function.
