### ISSUE TITLE
Resetting innerText

### ISSUE THREAD

**Issue by Glombort** [sonianb/github-profile-analyser#16]
https://github.com/sonianb/github-profile-analyser/blob/2bcc90743bd6079fc063d4520285719f5c2ad249/script.js#L112-L113

I think the first line of this is made redundant by the second, as it sets it to 'no recent...' and reinitialises the innerText for it. But on line 44 it is necessary as you're appending children and not setting the inner html explicitly.

**Comment by sonianb** [comment]
Closed by #17
