### ISSUE TITLE
Separation of concerns: charts.js vs script.js

### ISSUE THREAD

**Issue by joe-dev-public** [sonianb/github-profile-analyser#37]
A few bits of ``charts.js``, e.g. stuff like

https://github.com/sonianb/github-profile-analyser/blob/7736990c8bd827308240df9c03b453f133a436d3/charts.js#L17

look like they should be in ``script.js`` instead? e.g. similar to:

https://github.com/sonianb/github-profile-analyser/blob/7736990c8bd827308240df9c03b453f133a436d3/script.js#L130

On the whole the "modular structure" of the code looks good, but a few bits have crept in to functions like ``createPieChart`` that ideally should not be there? :)

**Comment by sonianb** [comment]
Closed by #40
